#!/bin/zsh

# GIT
br()  { git checkout -b ${1} && git branch --set-upstream-to=origin/${1} ${1} }
gdd()  { git --no-pager diff --stat ${1} }
gdff() { git --no-pager diff --stat ${1} }

# GREP and FIND
alias y='grep -Ri'
alias n='grep -Rvi'

# Recursively check current directory for files containing your argument
alias bigrep="find -type f | xargs grep -in --color=always "

# LS
alias ls='ls --color --group-directories-first'
alias l='ls -lAh'
alias ll='ls -l'
alias llh='ls -lh'
alias la='ls -lA'
alias lah='ls -lAh'

# CD
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../../'
alias .6='cd ../../../../../../'
alias .7='cd ../../../../../../../'
alias .8='cd ../../../../../../../../'

# DU
alias ducks='du -ckhs * | sort -hr'
alias coin='du -cks *  | sort -rn | head -n 10'
alias coincoin='du -ckhs *  | sort -hr | head -n 10'
alias mmv='noglob zmv -W'

alias watch='watch -c '

# SPY
# returns list of open internet sockets, optionally filter (via grep) for
# host/process/user/etc by adding an argument.
spy() { lsof -i -P +c 0 +M -n | grep -i "$1" }
spyn() { lsof -i -P +c 0 +M | grep -i "$1" }

# MISC
alias c='clear'
# alias a='vim ~/.minimics/aliases/aliases'
alias aloc='vim ~/.aliases.local'

# YOLO AND STUFF FOR YOLO PEOPLE
alias stfu='shutdown -h now'
alias chmog='chmod'

wiki()  { if [ "${1}" ]; then dig +short "${1}".wp.dg.cx TXT; fi }
weather() { curl "wttr.in/${1:-paris}?0pq&lang=fr" }
alias meteo=weather

getcert() { echo | openssl s_client -showcerts -servername ${1} -connect ${1}:443 2>/dev/null | openssl x509 -inform pem -noout -text }

# Please export these variables in ~/.aliases.local file
# ROLESKEL_PATH: a path to an actual ansible role skel
# GIT_EMAIL: your git email
# GIT_USERNAME: your git username
# GIT_SERVER: the remote of your ansible projects
# GIT_SERVER_URL: the URL to create a repository for your projet
mkrole() {
  if [ $# -eq 1 ]; then
    ansible-galaxy init \
      --role-skeleton=${ROLESKEL_PATH:-"~/.minimics/ansible/ansible-role-skel"} $1
    cd $1
    # rm -rf .git/
    git init
    git config user.email ${GIT_EMAIL}
    git config user.name ${GIT_USERNAME}
    git add *
    git commit -am 'feat(template): add initial role files'
    git remote
    git remote add origin \
      ${GIT_SSH_USERNAME:-git}@${GIT_SERVER:-github.com}:${GIT_USERNAME}/ansible-role-$1.git
    echo "Please add $1 project here: ${GIT_SERVER_URL:-https://github.com/new}"
    echo "When you're done, use 'git push'"
  else
    echo "Please add a role name."
  fi
}
#echo "Usage: ando <inventory> '<commands>' <hostname>"
ando() {
  cd ~/cpt-ansible.sys
  ansible -m shell -i inventories/${1} ${3} -a ${2}
}

reverse() {
  echo -e "IP ADDRESS  \tPING\tREVERSE"; for i in $(nmap -sL -n $1 | grep 'Nmap scan report for' | awk '{ print $5 }'); do echo -e "$i\t$(fping -c1 -t 100 $i > /dev/null 2>&1 && echo -e "\e[32mOK\e[39m" || echo -e "\e[31mKO\e[39m")\t$(dig +short +answer -x $i)"; done
}

solarized() {

  cat << EOF
SOLARIZED HEX      TERMCOL   XTERM/HEX    L*A*B        RGB           HSB
--------- -------  -------   -----------  ----------   -----------   -----------
base03    #002b36  brblack   234 #1c1c1c  15 -12 -12     0  43  54   193 100  21
base02    #073642  black     235 #262626  20 -12 -12     7  54  66   192  90  26
base01    #586e75  brgreen   240 #585858  45 -07 -07    88 110 117   194  25  46
base00    #657b83  bryellow  241 #626262  50 -07 -07   101 123 131   195  23  51
base0     #839496  brblue    244 #808080  60 -06 -03   131 148 150   186  13  59
base1     #93a1a1  brcyan    245 #8a8a8a  65 -05 -02   147 161 161   180   9  63
base2     #eee8d5  white     254 #e4e4e4  92 -00  10   238 232 213    44  11  93
base3     #fdf6e3  brwhite   230 #ffffd7  97  00  10   253 246 227    44  10  99
yellow    #b58900  yellow    136 #af8700  60  10  65   181 137   0    45 100  71
orange    #cb4b16  brred     166 #d75f00  50  50  55   203  75  22    18  89  80
red       #dc322f  red       160 #d70000  50  65  45   220  50  47     1  79  86
magenta   #d33682  magenta   125 #af005f  50  65 -05   211  54 130   331  74  83
violet    #6c71c4  brmagenta  61 #5f5faf  50  15 -45   108 113 196   237  45  77
blue      #268bd2  blue       33 #0087ff  55 -10 -45    38 139 210   205  82  82
cyan      #2aa198  cyan       37 #00afaf  60 -35 -05    42 161 152   175  74  63
green     #859900  green      64 #5f8700  60 -20  65   133 153   0    68 100  60

EOF

}

envtosecret() {
  grep -e '^[_a-zA-Z]\+=.\+$' $1 | awk -F '=' '{ "echo -n '\''"$2"'\'' | base64 -w0 | xargs" | getline var1 ; print $1": "var1 }'
}

secrettoenv() {
  grep -e '^ *[_a-zA-Z]\+: [=0-9A-Za-z]\+$' $1 | awk '{ "echo -n "$2" | base64 -d" | getline var1; print substr($1, 1, length($1)-1)"="var1 }'
}

alias x="kubectx"
alias ns="kubens"

alias yaourt='yay'

jl() {
  find ${1:-.} -name "*jsonnet" -print0 | xargs -0 -n1 -I % sh -c 'jsonnetfmt --test % || (echo Failed \($?\): % && exit 1)'
}

alias vim=nvim

alias ssd='systemctl --user stop syncthing.service ; systemctl --user status syncthing.service | cat'
alias sse='systemctl --user start syncthing.service ; systemctl --user status syncthing.service | cat'

alias track='vim ~/ypi.projects/horizon/$(date +%Gw%V) -o ~/ypi.projects/horizon/$(date +%Gw%V --date="last week")'
