# ENV
MINIMICS=$HOME/.minimics
DEFAULT_USER="ypiolet"
export EDITOR=vim

# OH MY ZSH
ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM="$MINIMICS/zsh/custom"

# VISUAL
POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(\
  status background_jobs rbenv virtualenv nvm rvm dir_writable root_indicator)
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="black"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_COLOR_SCHEME='dark'
# POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
# POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
# POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"

ZSH_THEME="powerlevel9k/powerlevel9k"

COMPLETION_WAITING_DOTS="true"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='bg=2'
#ZSH_THEME="agnoster"
#ZSH_THEME="jnrowe"
#ZSH_THEME="gianu"
eval `dircolors ~/.minimics/dircolors/solarized/dircolors.256dark`
export LESS_TERMCAP_mb=$(printf "\e[1;31m")
export LESS_TERMCAP_md=$(printf "\e[1;31m")
export LESS_TERMCAP_me=$(printf "\e[0m")
export LESS_TERMCAP_se=$(printf "\e[0m")
export LESS_TERMCAP_so=$(printf "\e[1;44;33m")
export LESS_TERMCAP_ue=$(printf "\e[0m")
export LESS_TERMCAP_us=$(printf "\e[1;32m")
export ZSH_THEME_TERM_TAB_TITLE_IDLE="$HOSTNAME"
export ZSH_THEME_TERM_TERM_TITLE_IDLE="$HOSTNAME"
export ZSH_THEME_TERM_TITLE_IDLE="$HOSTNAME"

# BEHAVIOR
HIST_STAMPS="yyyy-mm-dd"
DISABLE_UPDATE_PROMPT="true"
# DISABLE_AUTO_UPDATE="true"
# DISABLE_CORRECTION="true"
# CASE_SENSITIVE="true"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(vundle nmap screen theme taskwarrior cp sudo history systemd \
         docker docker-compose iwhois git node npm z kubectl helm terraform \
         ssh-agent \
         # zsh-autosuggestions \
         zsh-syntax-highlighting \
)
export ZSH_AUTOSUGGEST_USE_ASY=asyncmode
source $ZSH/oh-my-zsh.sh
source $ZSH/plugins/z/z.sh

# ALIASES
source $MINIMICS/aliases/aliases
source $HOME/.aliases.local

# ZSH PACKS
autoload -U zmv
case $TERM in
    xterm*)
        precmd () {print -Pn "\e]0;%n@%m: %~\a"}
        ;;
esac

export TENANT=cabestan
