source ~/.minimics/aliases/aliases
export TERM="xterm-256color"
eval `dircolors ~/.minimics/dircolors/solarized/dircolors.256dark`

# Keep 1000 lines of history and save it to ~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

